// Code generated by protoc-gen-go. DO NOT EDIT.
// source: engo-xaro.proto

package engoxaro

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_engo_xaro_d728998156398b54, []int{0}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_engo_xaro_d728998156398b54, []int{1}
}
func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (dst *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(dst, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Point struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_engo_xaro_d728998156398b54, []int{2}
}
func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (dst *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(dst, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Point) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type PlayerPositions struct {
	Positions            []*Point `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerPositions) Reset()         { *m = PlayerPositions{} }
func (m *PlayerPositions) String() string { return proto.CompactTextString(m) }
func (*PlayerPositions) ProtoMessage()    {}
func (*PlayerPositions) Descriptor() ([]byte, []int) {
	return fileDescriptor_engo_xaro_d728998156398b54, []int{3}
}
func (m *PlayerPositions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerPositions.Unmarshal(m, b)
}
func (m *PlayerPositions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerPositions.Marshal(b, m, deterministic)
}
func (dst *PlayerPositions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerPositions.Merge(dst, src)
}
func (m *PlayerPositions) XXX_Size() int {
	return xxx_messageInfo_PlayerPositions.Size(m)
}
func (m *PlayerPositions) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerPositions.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerPositions proto.InternalMessageInfo

func (m *PlayerPositions) GetPositions() []*Point {
	if m != nil {
		return m.Positions
	}
	return nil
}

type Player struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	ID                   int32    `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	IP                   string   `protobuf:"bytes,3,opt,name=IP,proto3" json:"IP,omitempty"`
	Position             *Point   `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_engo_xaro_d728998156398b54, []int{4}
}
func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (dst *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(dst, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Player) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Player) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *Player) GetPosition() *Point {
	if m != nil {
		return m.Position
	}
	return nil
}

type JoinGame struct {
	JoinMessage          string   `protobuf:"bytes,1,opt,name=joinMessage,proto3" json:"joinMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinGame) Reset()         { *m = JoinGame{} }
func (m *JoinGame) String() string { return proto.CompactTextString(m) }
func (*JoinGame) ProtoMessage()    {}
func (*JoinGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_engo_xaro_d728998156398b54, []int{5}
}
func (m *JoinGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinGame.Unmarshal(m, b)
}
func (m *JoinGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinGame.Marshal(b, m, deterministic)
}
func (dst *JoinGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinGame.Merge(dst, src)
}
func (m *JoinGame) XXX_Size() int {
	return xxx_messageInfo_JoinGame.Size(m)
}
func (m *JoinGame) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinGame.DiscardUnknown(m)
}

var xxx_messageInfo_JoinGame proto.InternalMessageInfo

func (m *JoinGame) GetJoinMessage() string {
	if m != nil {
		return m.JoinMessage
	}
	return ""
}

type PlayerLeft struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerLeft) Reset()         { *m = PlayerLeft{} }
func (m *PlayerLeft) String() string { return proto.CompactTextString(m) }
func (*PlayerLeft) ProtoMessage()    {}
func (*PlayerLeft) Descriptor() ([]byte, []int) {
	return fileDescriptor_engo_xaro_d728998156398b54, []int{6}
}
func (m *PlayerLeft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerLeft.Unmarshal(m, b)
}
func (m *PlayerLeft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerLeft.Marshal(b, m, deterministic)
}
func (dst *PlayerLeft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerLeft.Merge(dst, src)
}
func (m *PlayerLeft) XXX_Size() int {
	return xxx_messageInfo_PlayerLeft.Size(m)
}
func (m *PlayerLeft) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerLeft.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerLeft proto.InternalMessageInfo

func (m *PlayerLeft) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type PlayerJoined struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerJoined) Reset()         { *m = PlayerJoined{} }
func (m *PlayerJoined) String() string { return proto.CompactTextString(m) }
func (*PlayerJoined) ProtoMessage()    {}
func (*PlayerJoined) Descriptor() ([]byte, []int) {
	return fileDescriptor_engo_xaro_d728998156398b54, []int{7}
}
func (m *PlayerJoined) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerJoined.Unmarshal(m, b)
}
func (m *PlayerJoined) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerJoined.Marshal(b, m, deterministic)
}
func (dst *PlayerJoined) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerJoined.Merge(dst, src)
}
func (m *PlayerJoined) XXX_Size() int {
	return xxx_messageInfo_PlayerJoined.Size(m)
}
func (m *PlayerJoined) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerJoined.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerJoined proto.InternalMessageInfo

func (m *PlayerJoined) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlayerJoined) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "engoxaro.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "engoxaro.HelloReply")
	proto.RegisterType((*Point)(nil), "engoxaro.Point")
	proto.RegisterType((*PlayerPositions)(nil), "engoxaro.PlayerPositions")
	proto.RegisterType((*Player)(nil), "engoxaro.Player")
	proto.RegisterType((*JoinGame)(nil), "engoxaro.JoinGame")
	proto.RegisterType((*PlayerLeft)(nil), "engoxaro.PlayerLeft")
	proto.RegisterType((*PlayerJoined)(nil), "engoxaro.PlayerJoined")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// sends the greeting.
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// send the player who joined
	UserJoined(ctx context.Context, in *Player, opts ...grpc.CallOption) (*HelloReply, error)
	// send your position and receive every position of players
	SendPositions(ctx context.Context, in *Player, opts ...grpc.CallOption) (*PlayerPositions, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/engoxaro.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) UserJoined(ctx context.Context, in *Player, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/engoxaro.Greeter/UserJoined", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SendPositions(ctx context.Context, in *Player, opts ...grpc.CallOption) (*PlayerPositions, error) {
	out := new(PlayerPositions)
	err := c.cc.Invoke(ctx, "/engoxaro.Greeter/SendPositions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// sends the greeting.
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	// send the player who joined
	UserJoined(context.Context, *Player) (*HelloReply, error)
	// send your position and receive every position of players
	SendPositions(context.Context, *Player) (*PlayerPositions, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engoxaro.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_UserJoined_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Player)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).UserJoined(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engoxaro.Greeter/UserJoined",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).UserJoined(ctx, req.(*Player))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SendPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Player)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SendPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engoxaro.Greeter/SendPositions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SendPositions(ctx, req.(*Player))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "engoxaro.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
		{
			MethodName: "UserJoined",
			Handler:    _Greeter_UserJoined_Handler,
		},
		{
			MethodName: "SendPositions",
			Handler:    _Greeter_SendPositions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "engo-xaro.proto",
}

func init() { proto.RegisterFile("engo-xaro.proto", fileDescriptor_engo_xaro_d728998156398b54) }

var fileDescriptor_engo_xaro_d728998156398b54 = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x5f, 0xeb, 0xd3, 0x30,
	0x14, 0xfd, 0xa5, 0xbf, 0xfd, 0xe9, 0xee, 0x36, 0x27, 0x41, 0xa4, 0x1b, 0x3e, 0x94, 0x08, 0x32,
	0x70, 0xeb, 0xc3, 0x04, 0x1f, 0xf6, 0x20, 0x32, 0x26, 0x73, 0xa2, 0x50, 0x3a, 0x04, 0x5f, 0xab,
	0xbd, 0x96, 0x48, 0x97, 0x74, 0x69, 0x07, 0xed, 0x87, 0xf3, 0xbb, 0x49, 0xd2, 0xb5, 0xab, 0x9b,
	0xbe, 0xe5, 0xdc, 0x7b, 0x72, 0xee, 0x39, 0xb9, 0x81, 0x09, 0x8a, 0x58, 0x2e, 0x8b, 0x50, 0x49,
	0x2f, 0x55, 0x32, 0x97, 0xd4, 0xd6, 0x05, 0x8d, 0x19, 0x83, 0xd1, 0x47, 0x4c, 0x12, 0x19, 0xe0,
	0xe9, 0x8c, 0x59, 0x4e, 0x29, 0x74, 0x44, 0x78, 0x44, 0x87, 0xb8, 0x64, 0x3e, 0x08, 0xcc, 0x99,
	0xbd, 0x02, 0xb8, 0x70, 0xd2, 0xa4, 0xa4, 0x0e, 0xf4, 0x8f, 0x98, 0x65, 0x61, 0x5c, 0x93, 0x6a,
	0xc8, 0x5e, 0x42, 0xd7, 0x97, 0x5c, 0xe4, 0x74, 0x04, 0xa4, 0x30, 0x4d, 0x2b, 0x20, 0x85, 0x46,
	0xa5, 0x63, 0x55, 0xa8, 0x64, 0xef, 0x61, 0xe2, 0x27, 0x61, 0x89, 0xca, 0x97, 0x19, 0xcf, 0xb9,
	0x14, 0x19, 0x5d, 0xc2, 0x20, 0xad, 0x81, 0x43, 0xdc, 0xc7, 0xf9, 0x70, 0x35, 0xf1, 0x6a, 0x87,
	0x9e, 0x91, 0x0c, 0xae, 0x0c, 0x76, 0x82, 0x5e, 0xa5, 0x40, 0x67, 0x60, 0x7f, 0xcd, 0x50, 0xb5,
	0x0c, 0x37, 0x98, 0x3e, 0x01, 0x6b, 0xbf, 0x35, 0x63, 0xbb, 0x81, 0xb5, 0xdf, 0x1a, 0xec, 0x3b,
	0x8f, 0x86, 0x65, 0xed, 0x7d, 0xfa, 0x1a, 0xec, 0x5a, 0xd2, 0xe9, 0xb8, 0xe4, 0x5f, 0x33, 0x1b,
	0x02, 0x5b, 0x80, 0xfd, 0x49, 0x72, 0xb1, 0xd3, 0xc2, 0x2e, 0x0c, 0x7f, 0x49, 0x2e, 0xbe, 0xfc,
	0xf5, 0x06, 0xed, 0x12, 0x7b, 0x01, 0x50, 0x19, 0xfc, 0x8c, 0x3f, 0x73, 0x3d, 0x98, 0x47, 0x86,
	0x36, 0x0e, 0x2c, 0x1e, 0xb1, 0x35, 0x8c, 0xaa, 0xae, 0x56, 0xc4, 0xe8, 0xb6, 0xaf, 0x43, 0x9d,
	0xeb, 0x50, 0x56, 0x15, 0xaa, 0xc6, 0xab, 0xdf, 0x04, 0xfa, 0x3b, 0x85, 0x98, 0xa3, 0xa2, 0x6b,
	0xb0, 0x0f, 0x61, 0x69, 0x16, 0x43, 0x9f, 0x5f, 0xad, 0xb7, 0xb7, 0x39, 0x7b, 0x76, 0x57, 0x4f,
	0x93, 0x92, 0x3d, 0xd0, 0xb7, 0x00, 0xfa, 0xa1, 0x2e, 0x0e, 0x9e, 0xb6, 0x82, 0x1b, 0x67, 0xff,
	0xbd, 0xf7, 0x0e, 0xc6, 0x07, 0x14, 0xd1, 0x75, 0x75, 0xf7, 0x57, 0xa7, 0xb7, 0x95, 0x86, 0xcc,
	0x1e, 0x36, 0x0b, 0x98, 0x72, 0xe9, 0xc5, 0x2a, 0xfd, 0xe1, 0x61, 0x11, 0x1e, 0xd3, 0x04, 0xb3,
	0x86, 0xbe, 0x19, 0x7f, 0x10, 0xb1, 0xfc, 0x16, 0x2a, 0xe9, 0xeb, 0x3f, 0xea, 0x93, 0xef, 0x3d,
	0xf3, 0x59, 0xdf, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xb6, 0x28, 0xa8, 0xbf, 0x02, 0x00,
	0x00,
}
