// Code generated by protoc-gen-go. DO NOT EDIT.
// source: engo-xaro.proto

package engoxaro

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Player struct {
	Username             string               `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Id                   int32                `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Ip                   string               `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_engo_xaro_d12fa18130862c34, []int{0}
}
func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (dst *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(dst, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Player) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Player) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Player) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

func init() {
	proto.RegisterType((*Player)(nil), "engoxaro.Player")
}

func init() { proto.RegisterFile("engo-xaro.proto", fileDescriptor_engo_xaro_d12fa18130862c34) }

var fileDescriptor_engo_xaro_d12fa18130862c34 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0xcd, 0x41, 0xcb, 0x82, 0x30,
	0x1c, 0xc7, 0x71, 0xb6, 0x07, 0xc5, 0x67, 0x46, 0xc1, 0x4e, 0xc3, 0x4b, 0xd2, 0xc9, 0x4b, 0x13,
	0xea, 0xdc, 0x7b, 0x08, 0xa9, 0x73, 0x4c, 0xf6, 0x4f, 0x06, 0xea, 0x7f, 0xcc, 0x09, 0x75, 0xee,
	0x8d, 0x87, 0x1b, 0x76, 0xfc, 0xfd, 0xf8, 0xc0, 0x97, 0xed, 0x60, 0xec, 0xf0, 0xf8, 0x52, 0x0e,
	0xa5, 0x75, 0xe8, 0x91, 0x67, 0xcb, 0xb1, 0xec, 0x62, 0xdf, 0x21, 0x76, 0x3d, 0xd4, 0xe1, 0x6f,
	0xe7, 0x67, 0xed, 0xcd, 0x00, 0x93, 0x57, 0x83, 0x8d, 0xf4, 0xf0, 0x21, 0x2c, 0xbd, 0xf6, 0xea,
	0x0d, 0x8e, 0x17, 0x2c, 0x9b, 0x27, 0x70, 0xa3, 0x1a, 0x40, 0x90, 0x92, 0x54, 0xff, 0xcd, 0x6f,
	0xf3, 0x2d, 0xa3, 0x46, 0x0b, 0x5a, 0x92, 0x2a, 0x69, 0xa8, 0xd1, 0x61, 0x5b, 0xf1, 0x17, 0x14,
	0x35, 0x96, 0x5f, 0xd8, 0xa6, 0x57, 0x93, 0x7f, 0xcc, 0x56, 0x2b, 0x0f, 0x5a, 0x24, 0x25, 0xa9,
	0xf2, 0x53, 0x21, 0x63, 0x5e, 0xae, 0x79, 0x79, 0x5b, 0xf3, 0x4d, 0xbe, 0xf8, 0x7b, 0xe4, 0x6d,
	0x1a, 0xc0, 0xf9, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x11, 0xca, 0xc2, 0x82, 0xca, 0x00, 0x00, 0x00,
}
